### ISSUE TITLE
error: 'openssl/conf.h' file not found

### ISSUE THREAD

**Issue by johndpope** [VKoskiv/VaporCoin#1]
none of these answers helped. 
https://stackoverflow.com/questions/43415106/openssl-conf-h-file-not-found-error-on-macos-sierra

am using conda.

➜  VaporCoin git:(master) which openssl
/Users/johndpope/miniconda3/bin/openssl

could this help?
https://github.com/IBM-Swift/OpenSSL

I think a simple makefile with one liner does solve problem - or just add to readme.
**brew install openssl**

```
swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib
swift package -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib generate-xcodeproj

 .build/debug/Run
```

**Comment by vkoskiv** [comment]
Hey John. Which `Vapor` version are you running? You can check by running `vapor version` while in the root directory of the project.

**Comment by johndpope** [comment]
when I include the header linker paths -  it successfully builds and runs.
swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib
 

side note - I've been mining for > 10 minutes but still no dice. 
It would be great if this thing just spat out coins en masse. 

![screen shot 2018-01-09 at 11 45 11 am](https://user-images.githubusercontent.com/289994/34732213-9302fd7e-f532-11e7-9984-50acedc16591.png)

**Comment by vkoskiv** [comment]
I'm glad you took a look at my project, it's still very much a WIP. The blocks mined don't contain coinbase transactions yet :P

On your build issue: 
Are you sure you've got the latest version of the Vapor framework installed? `brew deps vapor` lists these dependencies:
ctls
openssl
pkg-config

**Comment by johndpope** [comment]
brew deps vapor
Error: No available formula with the name "vapor"

**Comment by johndpope** [comment]
do you have any idea how long to mine a block? also could ipfs play a roll here to host blockchain?
https://github.com/NeoTeo/IpfsIosAppExample

**Comment by vkoskiv** [comment]
Try running `brew install vapor`
Then in the project root dir, `vapor update`, `vapor build` and finally: `vapor run`
You may be missing the vapor framework!

To mine a block, you can drop down the difficulty by removing zeroes here: https://github.com/VKoskiv/VaporCoin/blob/41efaabc75dd286929db93778dd4617506c6d8fa/Sources/App/Models/Miner.swift#L53

**Comment by johndpope** [comment]
![screen shot 2018-01-09 at 11 53 05 am](https://user-images.githubusercontent.com/289994/34732581-aee568f0-f533-11e7-8448-bb97cfc4d96f.png)

brew install vapor/tap/vapor - working fine. thanks - will update PR.
