### ISSUE TITLE
not an issue - fyi blockchain-demo

### ISSUE THREAD

**Issue by johndpope** [VKoskiv/VaporCoin#5]
this demo on bitcoin (part 1/2) showcases a simple blockchain - I think this code base could leverage some of the ui stuff to push things along. 
https://anders.com/blockchain/

I try to stay away from javascript like the plague - but code is written in jade. 

![screen shot 2018-01-10 at 10 24 17 am](https://user-images.githubusercontent.com/289994/34780197-73124826-f5f0-11e7-8031-4bbbdd02f407.png)

![68747470733a2f2f696d672e796f75747562652e636f6d2f76692f5f3136306f4d7a626c59382f302e6a7067](https://user-images.githubusercontent.com/289994/34780093-223bd6d8-f5f0-11e7-8b30-3b227fef9e4f.jpg)
https://github.com/anders94/blockchain-demo

https://www.youtube.com/watch?v=_160oMzblY8&feature=youtu.be

probably any ui stuff should be done via api - I'm thinking ios / uitableviews using grpc or web json. 
Need to expose api.

**Comment by vkoskiv** [comment]
Good stuff!

Yeah - My intent is to keep the web UI super simple. Static pages that send commands to the node.

**Comment by vkoskiv** [comment]
This project is built ontop the Vapor framework, which is intended to be a server-side Swift framework for building websites with.
Implementing a web-UI should be trivial once the nodes are working properly and communicating.
