### ISSUE TITLE
clarification - on vapor / droplet threading DispatchQueue vs. OperationQueue

### ISSUE THREAD

**Issue by johndpope** [VKoskiv/VaporCoin#8]
in an attempt to bring some clarity to what's going on - started digging into the threading and surprised by this.

When we spawn the DispatchQueue.concurrentPerform this is not originating from the main thread to my surprise.

<img width="867" alt="screen shot 2018-01-11 at 12 09 34 pm" src="https://user-images.githubusercontent.com/289994/34837297-5bce0b36-f6c8-11e7-8606-7423fbbcf3fe.png">

I must admit, I am much more comfortable using operation queues which are built on top of GCD.
This simplified code - would fire up multiple operations to mine the block hash.
Once we find the hash - all queued operations are stopped.

this queue can be governed from other classes 
![screen shot 2018-01-11 at 12 12 57 pm](https://user-images.githubusercontent.com/289994/34837426-c8f9d906-f6c8-11e7-8694-1f7d5d64fbb9.png)

I'm thinking the mining should be able to get access to a main thread - that would help centralize state.

But doesn't seem like this code can run 

   DispatchQueue.main.async {
            print("hello") 
            // or do something more useful
        }

https://github.com/vapor/vapor/issues/1268

basically looking to do this

```swift

extension Droplet {
    public func setup() throws {
        try setupRoutes()
        
        //For now init state by reading value from there.
        print("BlockChain count: \(state.blockChain.count)")
        
        DispatchQueue.main.async { // this code won't run
            self.mine()
        }

    }
    
    func mine(){
       
            let miner = Miner(coinbase: "asdf", diff: 5000, threadCount: 4)
            let newBlock = Block(prevHash: state.getPreviousBlock().blockHash, depth: state.blockDepth, txns: [Transaction()], timestamp: Date().timeIntervalSince1970, difficulty: 5000, nonce: 0, hash: Data())
            miner.mineBlock(block: newBlock) { foundBlock in
                miner.blockFound(block: foundBlock) //Update state, print output
                
                DispatchQueue.main.async {
                    self.mine()
                }

            }
            
        
    }
    
}

```

**Comment by johndpope** [comment]
https://gist.github.com/johndpope/de0fbe9679ad8dd8b2cbc2b450f8b887

**Comment by vkoskiv** [comment]
Good findings! I'm really not too familiar with multithreading on Swift, so I just went with the first implementation that works. If you can make a PR for a better one (That doesn't crash!), that'd be great.
Ideally this project would compile and work under Ubuntu (The other OS supported by Vapor)
I believe GCD does work under Linux.

**Comment by johndpope** [comment]
so - I think I've progressed things quite well. will do a push shortly. 

some nomenclature -

the blockchain in the app is not actually / necessarily the production block chain.
in my mind it perhaps makes sense to refer to it the candidate blockchain which could diverge from production blockchain. 

why? - from reading last night there's something called blockchain reorganization which can invalidate a nodes' blockchain to the consensus network blockchain. if that makes sense.

**Comment by vkoskiv** [comment]
I agree.
I think we should keep valid but untrusted blocks in-memory, and only store blocks in the DB when they are absolutely trusted, like when a certain number of valid blocks after it have been received.
