### ISSUE TITLE
reasons why the miner should be decoupled into separate process

### ISSUE THREAD

**Issue by johndpope** [VKoskiv/VaporCoin#9]
if people want to use dedicated hardware - then the miner process would be decoupled from server.

**Comment by vkoskiv** [comment]
I agree - There should be facilities for a separate mining program, and there sort of is. See MinerProtocol.swift
I intend that to contain the protocol for communicating with specialized miner nodes.

For now though I feel it's appropriate to also have an integrated, simple CPU miner to get the network up and running.

**Comment by vkoskiv** [comment]
On a further note: Bitcoin had an integrated CPU miner in the beginning. I believe it's been removed in the later versions, however.
